function varargout = holography_export(varargin)
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @holography_export_OpeningFcn, ...
    'gui_OutputFcn',  @holography_export_OutputFcn, ...
    'gui_LayoutFcn',  @holography_export_LayoutFcn, ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

function holography_export_OpeningFcn(hObject, eventdata, handles, varargin)
handles.output = hObject;

% Global Variant
handles.lambda  = 532.8;
handles.dist    = 0;
handles.ccd     = 5;
handles.oriFlag = 0;
handles.bgFlag  = 0;
handles.brightness = 6;
handles.img     = 0;
handles.bg = 0;
% Global Filter switches
handles.filter = 'rdWindow';
handles.filter_med = 0;
handles.filter_mean = 0;
guidata(hObject, handles);

function varargout = holography_export_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.output;

function slider1_Callback(hObject, eventdata, handles)
handles.brightness = get(hObject,'Value') * 30;
axes(handles.dhPic);
imshow(handles.img * handles.brightness);
guidata(hObject,handles)

function slider1_CreateFcn(hObject, eventdata, handles)
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
set(hObject,'Value',0.2);
guidata(hObject,handles)

function saveBtn_Callback(hObject, eventdata, handles)
[fname,pname,ext] = uiputfile({'*.bmp','BMP (*.bmp)';'*.jpg','JPEG (*.jpg)';'*.tif','TIF (*.tif)'}, '保存全息图');
imwrite(handles.img * handles.brightness, [pname,fname]);

function oriPic_CreateFcn(hObject, eventdata, handles)
set(gca,'Visible','off');

function bgPic_CreateFcn(hObject, eventdata, handles)
set(gca,'Visible','off');

function dhPic_CreateFcn(hObject, eventdata, handles)
set(gca,'Visible','off');

function oriPic_ButtonDownFcn(hObject, eventdata, handles)
[fn, pn, fi] = uigetfile({'*.bmp','BMP (*.bmp)';'*.jpg','JPEG (*.jpg)';'*.tif','TIF (*.tif)'}, '选择原图');
if [fn, pn]
    axes(handles.oriPic);
    set(gca, 'Visible', 'on');
    img = imread([pn fn]);
    handles.oriFlag = [pn, fn];
    imshow(img);
    guidata(hObject,handles)
end

function oriPanel_ButtonDownFcn(hObject, eventdata, handles)
[fn, pn, fi] = uigetfile({'*.bmp','BMP (*.bmp)';'*.jpg','JPEG (*.jpg)';'*.tif','TIF (*.tif)'}, '选择原图');
if [fn, pn]
    axes(handles.oriPic);
    set(gca, 'Visible', 'on');
    img = imread([pn fn]);
    imshow(img);
    handles.oriFlag = [pn, fn];
    guidata(hObject,handles)
end

function bgPic_ButtonDownFcn(hObject, eventdata, handles)
[fn, pn, fi] = uigetfile({'*.bmp','BMP (*.bmp)';'*.jpg','JPEG (*.jpg)';'*.tif','TIF (*.tif)'}, '选择背景图');
if [fn, pn]
    axes(handles.bgPic);
    set(gca, 'Visible', 'on');
    img = imread([pn fn]);
    imshow(img);
    handles.bgFlag = [pn, fn];
    guidata(hObject,handles)
end

function bgPanel_ButtonDownFcn(hObject, eventdata, handles)
[fn, pn, fi] = uigetfile({'*.bmp','BMP (*.bmp)';'*.jpg','JPEG (*.jpg)';'*.tif','TIF (*.tif)'}, '选择背景图');
if [fn, pn]
    axes(handles.bgPic);
    set(gca, 'Visible', 'on');
    img = imread([pn fn]);
    handles.bgFlag = [pn, fn];
    imshow(img);
    guidata(hObject,handles)
end

function lambda_Callback(hObject, eventdata, handles)
lambda = str2double(get(hObject, 'String'));
if isnan(lambda)
    set(hObject, 'String', 532.8);
    errordlg('请输入正确的数字！', '错误');
else
    handles.lambda = lambda;
end
guidata(hObject,handles)

function lambda_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function edDist_Callback(hObject, eventdata, handles)
dist = str2double(get(hObject, 'String'));
if isnan(dist)
    set(hObject, 'String', 0);
    errordlg('请输入正确的数字！', '错误');
else
    handles.dist = dist;
end
guidata(hObject,handles)

function edDist_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function ccd_Callback(hObject, eventdata, handles)
ccd = str2double(get(hObject, 'String'));
if isnan(ccd)
    set(hObject, 'String', 5.0);
    errordlg('请输入正确的数字！', '错误');
else
    handles.ccd = ccd;
end
guidata(hObject,handles)

function ccd_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function calcBtn_Callback(hObject, eventdata, handles)
set(handles.txtWarn, 'Visible', 'off');
if (~handles.oriFlag)
    errordlg('请选择原图！', '错误');
else
    handles.img = imread(handles.oriFlag);
    if (handles.bgFlag)
        handles.bg  = imread(handles.bgFlag);
        if (size(handles.img) == size(handles.bg))
            handles.img  = imsubtract(handles.img, handles.bg);
        else
            set(handles.txtWarn, 'string', '原图与背景图尺寸不符，使用默认背景!');
            set(handles.txtWarn, 'Visible', 'on');
        end
    end
    
    if(size(size(handles.img), 2) > 2) 
        handles.img=rgb2gray(handles.img);
    end
    % before calculate
    switch handles.filter
        case 'rdWindow'
            handles.img = WindowFilter(handles.img);
        case 'rdLaplace'
            handles.img = LaplaceFilter(handles.img);
    end
    % calculate
    handles.img = calculate(handles.img, handles.lambda / 1000, handles.dist * 1000, handles.ccd);
    % after calculate
    if (handles.filter_med)
        handles.img = MedianFilter(handles.img);
    end
    if (handles.filter_mean)
        handles.img = MeanFilter(handles.img);
    end
    axes(handles.dhPic);
    set(gca, 'Visible', 'on');
    imshow(handles.img * handles.brightness);
    guidata(hObject,handles)
end

function cbMed_Callback(hObject, eventdata, handles)
handles.filter_med = get(hObject, 'value');
guidata(hObject,handles);

function ctrlPanle_SelectionChangeFcn(hObject, eventdata, handles)
handles.filter = get(hObject,'Tag');
guidata(hObject,handles);

function slider2_Callback(hObject, eventdata, handles)
set(handles.edDist,'String', (handles.dist + get(hObject, 'Value') - 0.5) * 20);
guidata(hObject,handles)

function slider2_CreateFcn(hObject, eventdata, handles)
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
set(hObject,'Value',0.5);
guidata(hObject,handles)

function cbMean_Callback(hObject, eventdata, handles)
handles.filter_mean = get(hObject, 'value');
guidata(hObject,handles);


% --- Creates and returns a handle to the GUI figure. 
function h1 = holography_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load holography_export.mat


appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'uipanel', 7, ...
    'slider', 3, ...
    'pushbutton', 3, ...
    'axes', 4, ...
    'edit', 4, ...
    'text', 15, ...
    'checkbox', 8, ...
    'radiobutton', 8, ...
    'popupmenu', 4), ...
    'override', 0, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'F:\matlab\digital-holography\matlab-version\holography_export.m', ...
    'lastFilename', 'F:\matlab\digital-holography\matlab-version\holography.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','holography',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[103.8 34.6923076923077 185.6 28.3846153846154],...
'Resize','off',...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'oriPanel';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',10,...
'Title','原图',...
'ButtonDownFcn',@(hObject,eventdata)holography_export('oriPanel_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Clipping','on',...
'Position',[4.2 17.3076923076923 38 11],...
'Tag','oriPanel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'oriPic';

h3 = axes(...
'Parent',h2,...
'Units','characters',...
'Position',[2.6 0.692307692307692 32.4 8.92307692307692],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'LooseInset',[4.836 1.06615384615385 3.534 0.726923076923077],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'ButtonDownFcn',@(hObject,eventdata)holography_export('oriPic_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('oriPic_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','oriPic',...
'Visible','off');

h4 = get(h3,'title');

set(h4,...
'Parent',h3,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.496913580246914 1.05603448275862 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h5 = get(h3,'xlabel');

set(h5,...
'Parent',h3,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.496913580246914 -0.202586206896552 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h6 = get(h3,'ylabel');

set(h6,...
'Parent',h3,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.175925925925926 0.487068965517241 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h7 = get(h3,'zlabel');

set(h7,...
'Parent',h3,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.225308641975309 1.13362068965517 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'bgPanel';

h8 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',10,...
'Title','背景图',...
'ButtonDownFcn',@(hObject,eventdata)holography_export('bgPanel_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Clipping','on',...
'Position',[4.2 5.76923076923079 38 11],...
'Tag','bgPanel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'bgPic';

h9 = axes(...
'Parent',h8,...
'Units','characters',...
'Position',[2.6 0.692307692307692 32.4 8.92307692307692],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'LooseInset',[4.836 1.06615384615385 3.534 0.726923076923077],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'ButtonDownFcn',@(hObject,eventdata)holography_export('bgPic_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('bgPic_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','bgPic',...
'Visible','off');

h10 = get(h9,'title');

set(h10,...
'Parent',h9,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.496913580246914 1.05603448275862 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h11 = get(h9,'xlabel');

set(h11,...
'Parent',h9,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.496913580246914 -0.202586206896552 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h12 = get(h9,'ylabel');

set(h12,...
'Parent',h9,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.175925925925926 0.487068965517242 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h13 = get(h9,'zlabel');

set(h13,...
'Parent',h9,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.225308641975309 2.42672413793103 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'dhPanel';

h14 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',10,...
'Title','全息图',...
'Clipping','on',...
'Position',[85.4 1.00000000000001 97.2 27.3076923076923],...
'Tag','dhPanel',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'dhPic';

h15 = axes(...
'Parent',h14,...
'Units','characters',...
'Position',[1.8 0.692307692307688 92.8 25.1538461538462],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'LooseInset',[4.836 1.06615384615385 3.534 0.726923076923077],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'ZColor',get(0,'defaultaxesZColor'),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('dhPic_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','dhPic',...
'Visible','off');

h16 = get(h15,'title');

set(h16,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.498922413793103 1.01987767584098 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h17 = get(h15,'xlabel');

set(h17,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.498922413793103 -0.0718654434250763 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h18 = get(h15,'ylabel');

set(h18,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.0614224137931035 0.496941896024465 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h19 = get(h15,'zlabel');

set(h19,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.945043103448276 1.05045871559633 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'slider1';

h20 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[0.9 0.9 0.9],...
'Callback',@(hObject,eventdata)holography_export('slider1_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[4 3.46153846153848 78 1.53846153846154],...
'String',{  '滑块' },...
'Style','slider',...
'Value',0.2,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('slider1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','slider1');

appdata = [];
appdata.lastValidTag = 'saveBtn';

h21 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback',@(hObject,eventdata)holography_export('saveBtn_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[29.6 0.846153846153851 20.2 1.84615384615385],...
'String','保存',...
'ButtonDownFcn',@(hObject,eventdata)holography_export('saveBtn_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Tag','saveBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'calcBtn';

h22 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback',@(hObject,eventdata)holography_export('calcBtn_Callback',hObject,eventdata,guidata(hObject)),...
'KeyPressFcn',@(hObject,eventdata)holography_export('calcBtn_KeyPressFcn',hObject,eventdata,guidata(hObject)),...
'Position',[4.4 0.846153846153851 20.2 1.84615384615385],...
'String','计算',...
'Tag','calcBtn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ctrlPanle';

h23 = uibuttongroup(...
'Parent',h1,...
'Units','characters',...
'FontSize',10,...
'Title','参数',...
'ButtonDownFcn',@(hObject,eventdata)holography_export('ctrlPanle_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'Clipping','on',...
'Position',[44 12 38.2 16.3076923076923],...
'Tag','ctrlPanle',...
'SelectedObject',[],...
'SelectionChangeFcn',@(hObject,eventdata)holography_export('ctrlPanle_SelectionChangeFcn',get(hObject,'SelectedObject'),eventdata,guidata(get(hObject,'SelectedObject'))),...
'OldSelectedObject',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text12';

h24 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'FontSize',10,...
'Position',[1.8 4.84615384615386 16 2.30769230769231],...
'String','原图滤波处理',...
'Style','text',...
'Tag','text12',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h25 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'FontSize',10,...
'Position',[0.8 7.53846153846155 14.2 1.61538461538462],...
'String','像元大小',...
'Style','text',...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text11';

h26 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'CData',[],...
'FontSize',10,...
'Position',[27 7.53846153846155 8 1.61538461538462],...
'String','μm',...
'Style','text',...
'UserData',[],...
'Tag','text11',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text5';

h27 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'CData',[],...
'FontSize',10,...
'Position',[27 12.9230769230769 8 1.61538461538462],...
'String','nm',...
'Style','text',...
'UserData',[],...
'Tag','text5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text10';

h28 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'CData',[],...
'FontSize',10,...
'Position',[27.2 10.7692307692308 8 1.61538461538462],...
'String','mm',...
'Style','text',...
'UserData',[],...
'Tag','text10',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text4';

h29 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'FontSize',10,...
'Position',[0.6 10.7692307692308 14.2 1.61538461538462],...
'String','衍射距离',...
'Style','text',...
'Tag','text4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'ccd';

h30 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)holography_export('ccd_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10,...
'Position',[13.6 7.61538461538463 13.8 1.76923076923077],...
'String','5.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('ccd_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','ccd');

appdata = [];
appdata.lastValidTag = 'edDist';

h31 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)holography_export('edDist_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10,...
'Position',[13.8 10.8461538461539 13.8 1.76923076923077],...
'String','0.0',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('edDist_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edDist');

appdata = [];
appdata.lastValidTag = 'lambda';

h32 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)holography_export('lambda_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10,...
'Position',[13.8 13 13.8 1.76923076923077],...
'String','532.8',...
'Style','edit',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('lambda_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','lambda');

appdata = [];
appdata.lastValidTag = 'text1';

h33 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'FontSize',10,...
'Position',[5.2 12.8461538461539 8 1.61538461538462],...
'String','波长λ',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'rdLaplace';

h34 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'Callback',mat{1},...
'CData',[],...
'FontSize',10,...
'Position',[5.6 2.07692307692308 20.2 1.76923076923077],...
'String','拉普拉斯滤波',...
'Style','radiobutton',...
'UserData',[],...
'Tag','rdLaplace',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'rdWindow';

h35 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'Callback',mat{2},...
'CData',[],...
'FontSize',10,...
'Position',[5.6 0.307692307692317 26.6 1.76923076923077],...
'String','窗函数滤波',...
'Style','radiobutton',...
'Value',1,...
'UserData',[],...
'Tag','rdWindow',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'rdNone';

h36 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'Callback',mat{3},...
'FontSize',10,...
'Position',[5.6 3.84615384615386 22.6 1.76923076923077],...
'String','不处理',...
'Style','radiobutton',...
'Tag','rdNone',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'slider2';

h37 = uicontrol(...
'Parent',h23,...
'Units','characters',...
'BackgroundColor',[0.9 0.9 0.9],...
'Callback',@(hObject,eventdata)holography_export('slider2_Callback',hObject,eventdata,guidata(hObject)),...
'Position',[13.4 9.61538461538462 14.2 1],...
'String',{  '滑块' },...
'Style','slider',...
'Value',0.5,...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)holography_export('slider2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','slider2');

appdata = [];
appdata.lastValidTag = 'uipanel6';

h38 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontSize',10,...
'Title','全息图像去噪',...
'Clipping','on',...
'Position',[44 6.15384615384617 38.2 5.69230769230769],...
'Tag','uipanel6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cbMean';

h39 = uicontrol(...
'Parent',h38,...
'Units','characters',...
'Callback',@(hObject,eventdata)holography_export('cbMean_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',10,...
'Position',[3.4 2.30769230769231 15.2 1.76923076923077],...
'String','均值滤波',...
'Style','checkbox',...
'UserData',[],...
'Tag','cbMean',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'cbMed';

h40 = uicontrol(...
'Parent',h38,...
'Units','characters',...
'Callback',@(hObject,eventdata)holography_export('cbMed_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10,...
'Position',[3.4 0.538461538461539 16.2 1.76923076923077],...
'String','中值滤波',...
'Style','checkbox',...
'Tag','cbMed',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'txtWarn';

h41 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'ForegroundColor',[1 0 0],...
'HorizontalAlignment','left',...
'Position',[54.2 0.230769230769231 22 2.53846153846154],...
'String',{  '原图与背景图尺寸不符'; '使用默认背景!' },...
'Style','text',...
'Tag','txtWarn',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % HOLOGRAPHY_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % HOLOGRAPHY_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % HOLOGRAPHY_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % HOLOGRAPHY_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
    %workaround for CreateFcn not called to create ActiveX
    if feature('HGUsingMATLABClasses')
        peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
        for i=1:length(peers)
            if isappdata(peers(i),'Control')
                actxproxy(peers(i));
            end            
        end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


